version: '3.6'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    << : *restart_policy
    image: postgres:12
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3254:5432"

  graphql-engine:
    << : *restart_policy
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    volumes:
    - ./migrations:/hasura-migrations
    - ./metadata:/hasura-metadata
    depends_on:
    - "postgres"
    network_mode: "host"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@localhost:3254/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\":\"HS256\",\"key\":\"${HASURA_JWT_SECRET}\",\"claims_format\":\"json\",\"issuer\":\"${HASURA_JWT_ISSUER}\"}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    command: "graphql-engine serve"

volumes:
  db_data:
